<!-- Gallery -->
<div id="gallery" class="main">
	<ul class="project_images">
		<li id="<?= $this->project['id'] ?>" class="active"><?= "<img src=\"/uploads/{$this->project['image']['file_name']}\" alt=\"Primary Image\" />"; ?></li>
	</ul>
	<div class="controls_wrapper">
		<div class="gallery_controls main">
			<h2><?= $this->project['title'] ?></h2>
			<p><?= $this->truncate($this->project['description'], 20) ?></p>
			<ul class="nav gallery clearfix">
				<li class="left"><a href="#"></a></li>
				<li class="launch_btn"><a href="work/project/id/<?= $this->project['id'] ?>">Launch Project</a></li>
				<li class="right"><a href="#"></a></li>
			</ul>
		</div>
	</div>
</div>
<!-- Callouts -->
<ul class="callouts main clearfix">
	<li class="who">
		<h3>Who</h3>
		<p>Cras posuere eleifend pulvinar. Phasellus gravida ultrices porta. Praesent vulputate volutpat ligula, vitae dictum metus consectetur vitae.</p>
	</li>
	<li class="why">
		<h3>Why</h3>
		<p>Cras posuere eleifend pulvinar. Phasellus gravida ultrices porta. Praesent vulputate volutpat ligula, vitae dictum metus consectetur vitae.</p>
	</li>
	<li class="how">
		<h3>How</h3>
		<p>Cras posuere eleifend pulvinar. Phasellus gravida ultrices porta. Praesent vulputate volutpat ligula, vitae dictum metus consectetur vitae.</p>
	</li>
</ul>