<!-- Gallery -->
<div id="gallery" class="secondary">
	<ul>
		<li><img src="/images/image_01.png" alt="image" /></li>
	</ul>
	<div class="controls_wrapper"><!-- !Controlswrapper --></div>
</div>
<!-- Callouts -->
<ul class="callouts work clearfix">
	<li>
		<strong>Project:</strong>
		<h3>McMenamins Mobile</h3>
	</li>
	<li>
		<h3>About The Project</h3>
		<p>Cras posuere eleifend pulvinar. Phasellus gravida ultrices porta. Praesent vulputate volutpat ligula, vitae dictum metus consectetur vitae.</p>
	</li>
	<li>
		<h3>Project Contributions</h3>
		<ul class="normal">
			<li>(X)HTML</li>
			<li>CSS</li>
			<li>JQuery</li>
		</ul>
	</li>
	<li>
		<h3>Views</h3>
		<p>Cras posuere eleifend pulvinar. Phasellus gravida ultrices porta. Praesent vulputate volutpat ligula, vitae dictum metus consectetur vitae.</p>
	</li>
</ul>
<div id="thumbs">
	<ul class="clearfix">
		<li>
			<a href="#">
				<img src="/images/image_01.png" alt="thumb" />
			</a>
		</li>
		<li>
			<a href="#">
				<img src="/images/image_01.png" alt="thumb" />
			</a>
		</li>
		<li class="active">
			<a href="#">
				<img src="/images/image_01.png" alt="thumb" />
			</a>
		</li>
		<li>
			<a href="#">
				<img src="/images/image_01.png" alt="thumb" />
			</a>
		</li>
		<li>
			<a href="#">
				<img src="/images/image_01.png" alt="thumb" />
			</a>
		</li>
	</ul>
</div>
