<!-- Gallery -->
<div id="gallery" class="work">
	<ul>
		<li><img src="/images/image_01.jpg" alt="image" /></li>
	</ul>
</div>
<!-- Callouts -->
<ul class="callouts work clearfix">
	<li>
		<h3>EnCompass</h3>
	</li>
	<li>
		<h3>About The Project</h3>
		<p>Cras posuere eleifend pulvinar. Phasellus gravida ultrices porta. Praesent vulputate volutpat ligula, vitae dictum metus consectetur vitae.</p>
	</li>
	<li>
		<h3>Technology</h3>
		<p>Cras posuere eleifend pulvinar. Phasellus gravida ultrices porta. Praesent vulputate volutpat ligula, vitae dictum metus consectetur vitae.</p>
	</li>
	<li>
		<h3>Views</h3>
		<p>Cras posuere eleifend pulvinar. Phasellus gravida ultrices porta. Praesent vulputate volutpat ligula, vitae dictum metus consectetur vitae.</p>
	</li>
</ul>
