<!-- Gallery -->
<div id="gallery" class="secondary">
	<ul class="project_images">
		<li><?= "<img src=\"/uploads/{$this->project['view']}\" alt=\"image 1\" />"; ?></li>
	</ul>
	<div class="controls_wrapper"><!-- !Controlswrapper --></div>
</div>
<!-- Callouts -->
<ul class="callouts work clearfix">
	<li class="title">
		<strong>Project:</strong>
		<h3><?= $this->project['title'] ?></h3>
		<?= (!$this->project['url'] == '') ? "<a class=\"button launch external\" href=\"http://{$this->project['url']}\"><span>Launch Project</span></a>" : ''?>
	</li>
	<li class="about">
		<h3>About The Project</h3>
		<p><?= $this->project['description'] ?></p>
	</li>
	<li class="contributions">
		<h3>Project Contributions</h3>
		<ul class="normal">
			<?php
				foreach ($this->project['contributions'] as $contribution) {
					echo "<li>{$contribution['contribution']}</li>";
				}
			?>
		</ul>
	</li>
	<li class="views">
		<h3>Views</h3>
		<ul class="project_views clearfix">
		<?php
			foreach ($this->project['images'] as $key => $image) {
				echo ($image['file_name'] == $this->project['view']) ? "<li class=\"active\" title=\"{$image['id']}\">" : "<li title=\"{$image['id']}\">";
				echo "<a href=\"/work/project/id/{$this->project['id']}/view/{$image['id']}\">";
				echo "<img src=\"/uploads/{$image['file_name']}\" alt=\"thumbnail\" />";
				echo "</a>";
				echo "</li>";
			}
		?>
	</ul>
	</li>
</ul>
<div id="thumbs">
	<span class="control left">
		<a class="left" href="#">left</a>
	</span>
	<span class="control right">
		<a class="right" href="#">right</a>
	</span>
	<ul class="thumbs clearfix">
	<?php
		foreach ($this->thumbs as $key => $thumb) {
			echo ($thumb['project_id'] == $this->project['id']) ? "<li id=\"thumb_{$thumb['project_id']}\" class=\"active\" >" : "<li id=\"thumb_{$thumb['project_id']}\" >";
			echo "<a href=\"/work/project/id/{$thumb['project_id']}\">";
			if (isset($thumb['file_name'])) {
				echo "<img src=\"/uploads/{$thumb['file_name']}\" alt=\"thumbnail\" />";
			} else {
				echo "<img src=\"/images/default_image.png\" alt=\"thumbnail\" />";
			}
			echo "</a>";
			echo "</li>";
		}
	?>
	</ul>
</div>
