<div id="gallery" class="secondary">
	<ul>
		<li><img src="/images/image_01.png" alt="image" /></li>
	</ul>
	<div class="controls_wrapper"><!-- --></div>
</div>
<!-- Callouts -->
<ul class="callouts contact clearfix">
	<li class="one_third contact">
		<h3>Contact</h3>
		<p>Hello! My name is Kellan Craddock and innovative interactive design gets me excited!</p><p>As an Interactive designer from Portland Oregon, I continually strive to blend engaging graphics with cutting edge programming techniques to create rich and informative user experiences.</p>
	</li>
	<li class="two_thirds">
		<form action="/contact/mail" id="contact_form" method="post">
 			<fieldset class="clearfix">
 				<legend>Contact Me</legend>
 				<p id="mail_status"><?= $this->mail_status['message'] ?></p>
 				<label>Name:</label>
 				<input type="text" name="name"/>
 				<label>Email:</label>
 				<input type="text" name="email"/>
 				
 				<label>Message:</label>
 				<textarea rows="5" name="message"></textarea>
 				
 				<button class="button" type="submit" name="submit">Submit</button>
 			</fieldset>
 		</form>
	</li>
</ul>