<div id="gallery" class="secondary">
	<ul>
		<li><img src="/images/image_01.png" alt="image" /></li>
	</ul>
	<div class="controls_wrapper"><!-- --></div>
</div>
<!-- Callouts -->
<ul class="callouts contact clearfix">
	<li class="one_third contact">
		<h3>Contact</h3>
		<p>Have some questions? Let&lsquo;s talk!</p>
		<p>If it&lsquo;s for work, fun, or just to say &ldquo;hi!&rdquo; Feel free to leave me a message and I&lsquo;ll get back to you promptly!</p>
	</li>
	<li class="two_thirds">
		<form action="/contact/mail" id="contact_form" method="post">
 			<fieldset class="clearfix">
 				<legend>Contact Me</legend>
 				<?php
 					if ($this->mail_status['status'] == 'success') {
 						echo "<h4>Thanks for the message, {$this->mail_status['name']}!</h4>";
 					} elseif(isset($this->mail_status['message'])) {
 						echo "<h4>Whoops!</h4>";
 						echo "<ul class=\"normal errors\">";
 						foreach ($this->mail_status['message'] as $message) {
 							echo "<li>{$message}</li>";
 						}
 						echo "</ul>";
 					}
 				?>
 				<label>Name:</label>
 				<input type="text" name="name"/>
 				<label>Email:</label>
 				<input type="text" name="email"/>
 				
 				<label>Message:</label>
 				<textarea rows="5" name="message"></textarea>
 				
 				<button class="button" type="submit" name="submit">Submit</button>
 			</fieldset>
 		</form>
	</li>
</ul>