<div id="gallery" class="secondary">
	<ul>
		<li><img src="/images/image_01.png" alt="image" /></li>
	</ul>
</div>
<!-- Callouts -->
<ul class="callouts contact clearfix">
	<li class="one_third contact">
		<h3>Contact</h3>
		<p>Hello! My name is Kellan Craddock and innovative interactive design gets me excited!</p><p>As an Interactive designer from Portland Oregon, I continually strive to blend engaging graphics with cutting edge programming techniques to create rich and informative user experiences.</p>
	</li>
	<li class="two_thirds">
		<form id="contact_form">
 			<fieldset class="clearfix">
 				<legend>Contact Me</legend>
 				<p id="message_status"></p>
 				<label>Name:</label>
 				<input type="text" name="name"/>
 				<label>Email:</label>
 				<input type="text" name="email"/>
 				
 				<label>Message:</label>
 				<textarea rows="5" name="message"></textarea>
 				
 				<button class="button" type="submit" name="submit">Submit</button>
 			</fieldset>
 		</form>
	</li>
</ul>
<div class="columns clearfix">
	<div class="column two_thirds">
		<h4 class="contact">Let&rsquo;s talk!
			<span>Get in Contact</span>
		</h4>
		<ul class="nav contact clearfix">
			<li>
				<a class="button email external" href="#">Contact Me</a>
			</li>
			<li>
				<a class="button facebook external" href="#">Facebook</a>
			</li>
			<li>
				<a class="button twitter external" href="#">Twitter</a>
			</li>
		</ul>
	</div>
	<div class="column one_third resume">
		<h4>Resume</h4>
		<a class="button pdf" href="#">Full PDF Resume</a>
		<dl>
			<dt>B.S. Web Design and Interactive Media</dt>
			<dd><strong>October 2005 &ndash; September 2009</strong> Art Institute of Portland</dd>
		</dl>
		
	</div>
</div>