<div id="gallery" class="secondary">
	<ul>
		<li><img src="/images/image_01.png" alt="image" /></li>
	</ul>
</div>
<!-- Callouts -->
<ul class="callouts about clearfix">
	<li class="who">
		<h3>Who</h3>
		<p>Hello! My name is Kellan Craddock and innovative interactive design gets me excited!</p><p>As an Interactive designer from Portland Oregon, I continually strive to blend engaging graphics with cutting edge programming techniques to create rich and informative user experiences.</p>
	</li>
	<li class="why">
		<h3>Why</h3>
		<p>I am passionate about communication. Understanding how graphics, programming, and information come together on the web to create effective user experiences drives my work.</p><p>Whether it&rsquo;s a single page website, a Rich Internet Application, or a full&ndash;blown content managed online presence, I consistently keep user experience on the forefront.</p>
	</li>
	<li class="how">
		<h3>How</h3>
		<p>I believe that websites can be both visually engaging and highly functional.</p><p>This means writing valid and well structured (X)HTML, separating content from presentation with CSS, utilizing Object Oriented programming techniques to script interactivity, and interfacing with server&ndash;side technology and web services. This also means designing intuitive navigation schemes, emphasizing good typography, and tailoring content and copy for readability.</p><p>Of course this also means keeping up wit current web technologies and design trends.</p>
	</li>
</ul>
<div class="columns clearfix">
	<div class="column two_thirds">
		<h4 class="contact">Let&rsquo;s talk!
			<span>Get in Contact</span>
		</h4>
		<ul class="nav contact clearfix">
			<li>
				<a class="button email external" href="#">Contact Me</a>
			</li>
			<li>
				<a class="button facebook external" href="#">Facebook</a>
			</li>
			<li>
				<a class="button twitter external" href="#">Twitter</a>
			</li>
		</ul>
	</div>
	<div class="column one_third resume">
		<h4>Resume</h4>
		<a class="button pdf" href="#">Full PDF Resume</a>
		<dl>
			<dt>B.S. Web Design and Interactive Media</dt>
			<dd><strong>October 2005 &ndash; September 2009</strong> Art Institute of Portland</dd>
		</dl>
		
	</div>
</div>