<div class="columns clearfix">
	<div class="column one_third">
		<h2>Site Administration</h2>
		<form id="login" action="/admin/login" method="post">
			<fieldset>
				<legend>Login</legend>
					<label for="user_name">User Name: </label>
					<input type="text" name="user_name" id="user_name" />
					<label for="password">Password: </label>
					<input type="password" name="password" id="password	" />
					<button class="button" type="submit">Submit</button>
			</fieldset>
		</form>
	</div>
</div>
