<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
	<title>Kellan Craddock</title>
	
	<link type="text/css" href="css/master.css" rel="stylesheet" />
	
	<script type="text/javascript" src="/javascript/jquery-1.3.2.min.js"></script>
	<script type="text/javascript" src="/javascript/jquery.pngFix.pack.js"></script>
	<script type="text/javascript">
		$(function() {
			$('body').pngFix(); 
		});
	</script>
</head>

<body>
	<div id="panel"><!-- --></div>
	<div id="wrapper">
		<h1 class="logo">Kellan Craddock</h1>
		<!-- Main Navigation -->
		<ul class="nav main clearfix">
			<li class="active"><a href="/">Home</a></li>
			<li><a href="/work">Work</a></li>
			<li><a href="#">About</a></li>
			<li><a href="#">Contact</a></li>
		</ul>
		<!-- Sub Navigation -->
		<ul class="nav sub clearfix">
			<li>subnav</li>
		</ul>
		<!-- Main Content -->
		<div id="main_container">
			<?= $this->layout()->content ?>
		</div>
		<!-- Footer Navigation -->
		<ul class="nav footer clearfix">
			<li>Footer</li>
		</ul>
	</div>
</body>
</html>